import { PlayerStats } from "../stats";
import { Team } from "../team";

export type Player = {
  _id: string;
  accelRating: number;
  age: number;
  agilityRating: number;
  awareRating: number;
  bCVRating: number;
  bigHitTrait: number;
  birthDay: number;
  birthMonth: number;
  birthYear: number;
  blockShedRating: number;
  breakSackRating: number;
  breakTackleRating: number;
  cITRating: number;
  capHit: number;
  capReleaseNetSavings: number;
  capReleasePenalty: number;
  carryRating: number;
  catchRating: number;
  changeOfDirectionRating: number;
  clutchTrait: number;
  college: string;
  confRating: number;
  contractBonus: number;
  contractLength: number;
  contractSalary: number;
  contractYearsLeft: number;
  coverBallTrait: number;
  dLBullRushTrait: number;
  dLSpinTrait: number;
  dLSwimTrait: number;
  desiredBonus: number;
  desiredLength: number;
  desiredSalary: number;
  devTrait: number;
  draftPick: number;
  draftRound: number;
  dropOpenPassTrait: number;
  durabilityGrade: number;
  experiencePoints: number;
  feetInBoundsTrait: number;
  fightForYardsTrait: number;
  finesseMovesRating: number;
  firstName: string;
  forcePassTrait: number;
  hPCatchTrait: number;
  height: number;
  highMotorTrait: number;
  hitPowerRating: number;
  homeState: number;
  homeTown: string;
  impactBlockRating: number;
  injuryLength: number;
  injuryRating: number;
  injuryType: number;
  intangibleGrade: number;
  isActive: boolean;
  isFreeAgent: boolean;
  isOnIR: boolean;
  isOnPracticeSquad: boolean;
  jerseyNum: number;
  jukeMoveRating: number;
  jumpRating: number;
  kickAccRating: number;
  kickPowerRating: number;
  kickRetRating: number;
  lBStyleTrait: number;
  lastName: string;
  leadBlockRating: number;
  legacyScore: number;
  manCoverRating: number;
  passBlockFinesseRating: number;
  passBlockPowerRating: number;
  passBlockRating: number;
  penaltyTrait: number;
  physicalGrade: number;
  playActionRating: number;
  playBallTrait: number;
  playRecRating: number;
  playerBestOvr: number;
  playerSchemeOvr: number;
  portraitId: number;
  posCatchTrait: number;
  position: string;
  powerMovesRating: number;
  predictTrait: number;
  presentationId: number;
  pressRating: number;
  productionGrade: number;
  pursuitRating: number;
  qBStyleTrait: number;
  reSignStatus: number;
  releaseRating: number;
  rookieYear: number;
  rosterGoalList: any;
  rosterId: number;
  routeRunDeepRating: number;
  routeRunMedRating: number;
  routeRunShortRating: number;
  runBlockFinesseRating: number;
  runBlockPowerRating: number;
  runBlockRating: number;
  runStyle: number;
  scheme: number;
  sensePressureTrait: number;
  signatureSlotList: any;
  sizeGrade: number;
  skillPoints: number;
  specCatchRating: number;
  speedRating: number;
  spinMoveRating: number;
  staminaRating: number;
  stats?: PlayerStats;
  stiffArmRating: number;
  strengthRating: number;
  stripBallTrait: number;
  tackleRating: number;
  team?: Team;
  teamId: number;
  teamSchemeOvr: number;
  throwAccDeepRating: number;
  throwAccMidRating: number;
  throwAccRating: number;
  throwAccShortRating: number;
  throwAwayTrait: number;
  throwOnRunRating: number;
  throwPowerRating: number;
  throwUnderPressureRating: number;
  tightSpiralTrait: number;
  toughRating: number;
  truckRating: number;
  weight: number;
  yACCatchTrait: number;
  yearsPro: number;
  zoneCoverRating: number;
};

export interface IPlayerResponse {
  body: Player;
  success: boolean;
}

export interface IGetPlayerQuery {
  include_stats?: boolean;
  include_team?: boolean;
}

export type receivingSortList =
  | "recCatches.asc"
  | "recCatches.desc"
  | "recCatchPct.asc"
  | "recCatchPct.desc"
  | "recDrops.asc"
  | "recDrops.desc"
  | "recLongest.asc"
  | "recLongest.desc"
  | "recTDs.asc"
  | "recTDs.desc"
  | "recYdsAfterCatch.asc"
  | "recYdsAfterCatch.desc"
  | "recYacPerCatch.asc"
  | "recYacPerCatch.desc"
  | "recYds.asc"
  | "recYds.desc"
  | "recYdsPerCatch.asc"
  | "recYdsPerCatch.desc"
  | "recYdsPerGame.asc"
  | "recYdsPerGame.desc";

export type passingSortList =
  | "passAtt.asc"
  | "passAtt.desc"
  | "passComp.asc"
  | "passComp.desc"
  | "passInts.asc"
  | "passInts.desc"
  | "passLongest.asc"
  | "passLongest.desc"
  | "passerRating.asc"
  | "passerRating.desc"
  | "passSacks.asc"
  | "passSacks.desc"
  | "passTDs.asc"
  | "passTDs.desc"
  | "passYds.asc"
  | "passYds.desc"
  | "passYdsPerAtt.asc"
  | "passYdsPerAtt.desc"
  | "passYdsPerGame.asc"
  | "passYdsPerGame.desc";

export type rushingSortList =
  | "rushAtt.asc"
  | "rushAtt.desc"
  | "rushBrokenTackles.asc"
  | "rushBrokenTackles.desc"
  | "rushFum.asc"
  | "rushFum.desc"
  | "rushLongest.asc"
  | "rushLongest.desc"
  | "rushTDs.asc"
  | "rushTDs.desc"
  | "rush20PlusYds.asc"
  | "rush20PlusYds.desc"
  | "rushYdsAfterContact.asc"
  | "rushYdsAfterContact.desc"
  | "rushYds.asc"
  | "rushYds.desc"
  | "rushYdsPerAtt.asc"
  | "rushYdsPerAtt.desc"
  | "rushYdsPerGame.asc"
  | "rushYdsPerGame.desc";

export type defenseSortList =
  | "defCatchAllowed.asc"
  | "defCatchAllowed.desc"
  | "defDeflections.asc"
  | "defDeflections.desc"
  | "defForcedFum.asc"
  | "defForcedFum.desc"
  | "defFumRec.asc"
  | "defFumRec.desc"
  | "defInts.asc"
  | "defInts.desc"
  | "defIntReturnYds.asc"
  | "defIntReturnYds.desc"
  | "defSacks.asc"
  | "defSacks.desc"
  | "defSafeties.asc"
  | "defSafeties.desc"
  | "defTDs.asc"
  | "defTDs.desc"
  | "defTotalTackles.asc"
  | "defTotalTackles.desc";

export type kickingSortList =
  | "kickPts.asc"
  | "kickPts.desc"
  | "kickPts.asc"
  | "kickPts.desc"
  | "fG50PlusAtt.asc"
  | "fG50PlusAtt.desc"
  | "fG50PlusMade.asc"
  | "fG50PlusMade.desc"
  | "fGLongest.asc"
  | "fGLongest.desc"
  | "fGMade.asc"
  | "fGMade.desc";

export type puntingSortList =
  | "puntsBlocked.asc"
  | "puntsBlocked.desc"
  | "puntsIn20.asc"
  | "puntsIn20.desc"
  | "puntLongest.asc"
  | "puntLongest.desc"
  | "puntTBs.asc"
  | "puntTBs.desc"
  | "puntNetYdsPerAtt.asc"
  | "puntNetYdsPerAtt.desc"
  | "puntNetYds.asc"
  | "puntNetYds.desc"
  | "puntAtt.asc"
  | "puntAtt.desc"
  | "puntYdsPerAtt.asc"
  | "puntYdsPerAtt.desc"
  | "puntYds.asc"
  | "puntYds.desc";

export type LeadersSortList =
  | receivingSortList
  | passingSortList
  | rushingSortList
  | defenseSortList
  | kickingSortList
  | puntingSortList;
